# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greetings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='greetings.proto',
  package='rabbitmq',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fgreetings.proto\x12\x08rabbitmq\"\x1e\n\tGreetings\x12\x11\n\tgreetings\x18\x01 \x01(\tb\x06proto3'
)




_GREETINGS = _descriptor.Descriptor(
  name='Greetings',
  full_name='rabbitmq.Greetings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='greetings', full_name='rabbitmq.Greetings.greetings', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['Greetings'] = _GREETINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Greetings = _reflection.GeneratedProtocolMessageType('Greetings', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGS,
  '__module__' : 'greetings_pb2'
  # @@protoc_insertion_point(class_scope:rabbitmq.Greetings)
  })
_sym_db.RegisterMessage(Greetings)


# @@protoc_insertion_point(module_scope)
