version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    stdin_open: true
    tty: true
  consumer:
    build: consumer/
    depends_on:
        - "rabbitmq"
    stdin_open: true
    tty: true
  producer:
    build: producer/
    ports:
      - "5000:5000"  
    depends_on:
        - "rabbitmq"

